aa: rand-m9-mstd0.5-inc1
amp: ture
amp_dtype: float16
amp_impl: native
aug_repeats: 0
aug_splits: 0
batch_size: 32
bce_loss: false
bce_pos_weight: null
bce_sum: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 1
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.5
color_jitter_prob: null
cooldown_epochs: 0
crop_pct: 0.888
cutmix: 0.0
cutmix_minmax: null
data: ""
data_dir: /home/ubuntu/stu_data/xujiajing_projects/datasets/RLU/train/
data_val_dir_0: /home/ubuntu/stu_data/xujiajing_projects/datasets/RLU/2019-1
data_val_dir_1: /home/ubuntu/stu_data/xujiajing_projects/datasets/RLU/2019-2
data_val_dir_2: /home/ubuntu/stu_data/xujiajing_projects/datasets/RLU/2020-2
dataset: ''
dataset_download: false
decay_epochs: 300 #30 #40 #65 #90
decay_milestones:
- 40 #65 #90
- 80 #130 #180
decay_rate: 0.8 #0.5 #0.1
device: cuda
device_modules: null
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.1
epoch_repeats: 0.0
epochs: 90
eval_metric: loss
experiment: ''
fast_norm: false
fuser: ''
gaussian_blur_prob: null
gp: null
grad_accum_steps: 1
grad_checkpointing: false
grayscale_prob: null
head_init_bias: null
head_init_scale: null
hflip: 0.5
img_size: null
in_chans: null
initial_checkpoint: ''
input_img_mode: null
input_key: null
input_size:
- 3
- 224
- 224
interpolation: ''
is_regression: true
jsd_loss: false
layer_decay: null
local_rank: 0
log_interval: 20
log_wandb: false
loss_fn: HuberLoss
lr: 2e-7
lr_base: 0.1
lr_base_scale: ''
lr_base_size: 256
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.
- 0.
- 0.
min_lr: 1e-8
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: ctflnet
model_ema_decay: 0.9998
model_ema_force_cpu: false
model_ema_warmup: false
model_kwargs: {}
modification: cbam_r=16, k=7, hubloss_mean
momentum: 0.9
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_classes: 1
opt: adamw
opt_betas: null
opt_eps: null
opt_kwargs: {}
output:
patience_epochs: 10
pin_mem: false
pretrained: false
pretrained_path: null
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: step #step #cosine
sched_on_updates: false
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std:
- 1.
- 1.
- 1.
sync_bn: false
synchronize_step: false
target_key: null
torchcompile: null
torchscript: false
train_crop_mode: null
train_interpolation: random
train_num_samples: 1
train_split: train
tta: 0
use_multi_epochs_loader: false
val_num_samples: null
val_split: validation
validation_batch_size: null
vflip: 0.5
warmup_epochs: 0
warmup_lr: 1.0e-05
warmup_prefix: false
weight_decay: 5.0e-2
worker_seeding: all
workers: 4
